# -*- coding: utf-8 -*-
"""Lung Augmentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pfxoPbU0NQ1Sh39dejXMa1psg18fe1DF

#**Augmentation**
"""

import numpy as np
from matplotlib import pyplot as plt
from skimage.transform import AffineTransform, warp
from skimage import io, img_as_ubyte
import random
import os
import cv2
from scipy.ndimage import rotate

import albumentations as A

images_to_generate=1180

from google.colab import drive
drive.mount('/content/drive')

images_path = '/content/drive/Shareddrives/CXR_Project/Code/Colab_Notebook/Full Inspired/NEW_MODEL_UNET/TRAIN_DATA_LUNG/Train_Aug/Image'
masks_path = '//content/drive/Shareddrives/CXR_Project/Code/Colab_Notebook/Full Inspired/NEW_MODEL_UNET/TRAIN_DATA_LUNG/Train_Aug/Mask'
img_augmented_path = '/content/drive/Shareddrives/CXR_Project/Code/Colab_Notebook/Full Inspired/NEW_MODEL_UNET/TRAIN_DATA_LUNG/Train_Aug/Image'
msk_augmented_path = '/content/drive/Shareddrives/CXR_Project/Code/Colab_Notebook/Full Inspired/NEW_MODEL_UNET/TRAIN_DATA_LUNG/Train_Aug/Mask'

images=[] # to store paths of images from folder
masks=[]

for im in os.listdir(images_path):  # read image name from folder and append its path into "images" array     
    images.append(os.path.join(images_path,im))

for msk in os.listdir(masks_path):  # read image name from folder and append its path into "images" array     
    masks.append(os.path.join(masks_path,msk))

images.sort()
masks.sort()

print(len(images))
print(len(masks))

aug = A.Compose([
                 A.Resize(512,512),
                 A.HorizontalFlip(),
                 A.ShiftScaleRotate(rotate_limit=10,border_mode=cv2.BORDER_CONSTANT),
                 A.RandomBrightnessContrast()
                ])

random.seed(42)

i=1   # variable to iterate till images_to_generate


while i<=images_to_generate : 
    number = random.randint(0, len(images)-1)  #PIck a number to select an image & mask
    image = images[number]
    mask = masks[number]
    print(image, mask)
    #image=random.choice(images) #Randomly select an image name
    original_image = io.imread(image)
    original_mask = io.imread(mask)
    
    augmented = aug(image=original_image, mask=original_mask)
    transformed_image = augmented['image']
    transformed_mask = augmented['mask']

        
    new_image_path= "%s/augmented_image_%s.jpeg" %(img_augmented_path, i)
    new_mask_path = "%s/augmented_mask_%s.tiff" %(msk_augmented_path, i)
    io.imsave(new_image_path, transformed_image)
    io.imsave(new_mask_path, transformed_mask)
    i =i+1